services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: botdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U botuser -d botdb"]
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - bot-network

  bot:
    build: .
    container_name: telegram_bot
    environment:
      - DATABASE_URL=postgresql://botuser:secretpass@db:5432/botdb
      - TOKEN=${TOKEN}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bot-network
    restart: unless-stopped
    command: ["sh", "-c", "sleep 5 && python bot_pg.py"]

volumes:
  db_data: {}

networks:
  bot-network: {}